# Generated by Django 3.1 on 2021-01-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210117_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expernce',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='publish',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vancy',
            field=models.IntegerField(default=1),
        ),
    ]
